"""schemas.py - Pipeline type definitions and parameter schemas."""

# Each pipeline type has bilingual fields:
#   label, description        → English (fallback)
#   label_zh, description_zh  → Chinese
# Each param has: label, description (EN) + label_zh, description_zh (ZH)

PIPELINE_TYPES = {
    "relief": {
        "label": "Bas-Relief",
        "description": "Convert an image to a 3D bas-relief — viewed from the front, reflective surface.",
        "label_zh": "浮雕 (Relief)",
        "description_zh": "将图片转换为 3D 浮雕 — 正面观赏，通过反射光呈现凹凸效果。支持 4 色 AMS 多色打印。",
        "script": "image-to-relief.py",
        "input": "image",
        "accepts": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "gpu": False,
        "params": [
            {"name": "width", "type": "float", "default": 160.0, "min": 20, "max": 500,
             "label": "Width (mm)", "label_zh": "宽度 (mm)", "description": "Target physical width", "description_zh": "目标物理宽度"},
            {"name": "height", "type": "float", "default": 120.0, "min": 20, "max": 500,
             "label": "Height (mm)", "label_zh": "高度 (mm)", "description": "Target physical height", "description_zh": "目标物理高度"},
            {"name": "max_depth", "type": "float", "default": 3.0, "min": 0.5, "max": 10.0,
             "label": "Max Depth (mm)", "label_zh": "最大深度 (mm)", "description": "Maximum relief depth", "description_zh": "浮雕最大凹凸深度"},
            {"name": "base_thickness", "type": "float", "default": 0.5, "min": 0.2, "max": 5.0,
             "label": "Base Thickness (mm)", "label_zh": "底厚 (mm)", "description": "Minimum base plate thickness", "description_zh": "底板最小厚度"},
            {"name": "detail", "type": "float", "default": 0.25, "min": 0.0, "max": 1.0,
             "label": "Detail Strength", "label_zh": "细节强度", "description": "Fine detail preservation (0=none, 1=full)", "description_zh": "精细细节保留程度（0=平滑无细节，1=保留全部细节）"},
            {"name": "colors", "type": "int", "default": 0, "min": 0, "max": 4,
             "label": "Colors", "label_zh": "颜色数", "description": "Quantize to N colors for AMS printing (0=mono)", "description_zh": "量化到 N 种颜色用于 AMS 多色打印（0=单色）"},
            {"name": "pixel_spacing", "type": "float", "default": 0.08, "min": 0.05, "max": 0.5,
             "label": "Pixel Spacing (mm)", "label_zh": "像素间距 (mm)", "description": "Resolution of height field", "description_zh": "高度场分辨率（越小越精细，文件越大）"},
        ]
    },
    "lithophane": {
        "label": "Lithophane",
        "description": "Convert an image to a backlit lithophane — thin areas let light through, thick areas block it.",
        "label_zh": "夜灯 (Lithophane)",
        "description_zh": "将图片转换为背光夜灯 — 薄处透光、厚处遮光。适合相框、灯罩等透光装饰品。",
        "script": "image-to-relief.py",
        "input": "image",
        "accepts": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "gpu": False,
        "params": [
            {"name": "width", "type": "float", "default": 160.0, "min": 20, "max": 500,
             "label": "Width (mm)", "label_zh": "宽度 (mm)", "description": "Target physical width", "description_zh": "目标物理宽度"},
            {"name": "height", "type": "float", "default": 120.0, "min": 20, "max": 500,
             "label": "Height (mm)", "label_zh": "高度 (mm)", "description": "Target physical height", "description_zh": "目标物理高度"},
            {"name": "max_depth", "type": "float", "default": 2.0, "min": 0.5, "max": 5.0,
             "label": "Max Depth (mm)", "label_zh": "最大厚度变化 (mm)", "description": "Thickness variation range", "description_zh": "厚薄变化范围（推荐 1.5-2.5mm）"},
            {"name": "base_thickness", "type": "float", "default": 0.6, "min": 0.3, "max": 3.0,
             "label": "Base Thickness (mm)", "label_zh": "最薄处厚度 (mm)", "description": "Minimum thickness (thinnest areas)", "description_zh": "最薄区域的厚度（决定透光量）"},
            {"name": "detail", "type": "float", "default": 0.15, "min": 0.0, "max": 1.0,
             "label": "Detail Strength", "label_zh": "细节强度", "description": "Fine detail preservation", "description_zh": "精细细节保留程度"},
            {"name": "colors", "type": "int", "default": 0, "min": 0, "max": 4,
             "label": "Colors", "label_zh": "颜色数", "description": "Quantize to N colors (0=mono)", "description_zh": "量化到 N 种颜色（0=单色）"},
        ]
    },
    "layered_relief": {
        "label": "Layered Color Relief",
        "description": "Single-mesh multi-colour relief via height banding. Different Z-height ranges map to different filament colours. Use with AMS / multi-material for automatic colour changes at layer heights.",
        "label_zh": "多层套色浮雕",
        "description_zh": "单 mesh 高度分色浮雕 — 不同 Z 高度区间对应不同耗材颜色，配合 AMS / 多材料系统自动换色打印。输出 STL + 换色高度说明 + 可选 3MF。",
        "script": "image-to-layered-relief.py",
        "input": "image",
        "accepts": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "gpu": False,
        "params": [
            {"name": "width", "type": "float", "default": 160.0, "min": 20, "max": 500,
             "label": "Width (mm)", "label_zh": "宽度 (mm)", "description": "Target physical width", "description_zh": "目标物理宽度"},
            {"name": "height", "type": "float", "default": 120.0, "min": 20, "max": 500,
             "label": "Height (mm)", "label_zh": "高度 (mm)", "description": "Target physical height", "description_zh": "目标物理高度"},
            {"name": "colors", "type": "int", "default": 4, "min": 2, "max": 16,
             "label": "Number of Colors", "label_zh": "颜色数", "description": "Number of filament colours. Each colour occupies an equal Z-height band.", "description_zh": "耗材颜色数量，每种颜色占据等高的 Z 区间。颜色越多过渡越细腻。"},
            {"name": "layer_height", "type": "float", "default": 0.4, "min": 0.2, "max": 1.0,
             "label": "Band Height (mm)", "label_zh": "颜色带高度 (mm)", "description": "Z-height per colour band. ≥0.4mm for full opacity with PLA.", "description_zh": "每种颜色的 Z 高度区间。PLA 建议 ≥0.4mm 以确保不透底色。"},
            {"name": "base_thickness", "type": "float", "default": 0.3, "min": 0.2, "max": 1.0,
             "label": "Base Thickness (mm)", "label_zh": "底板厚度 (mm)", "description": "Minimum base plate thickness (lowest Z).", "description_zh": "底板最小厚度（最底层 Z 起点）。"},
            {"name": "edge_smooth", "type": "float", "default": 0.5, "min": 0.0, "max": 1.0,
             "label": "Edge Smoothing", "label_zh": "边缘平滑", "description": "Anti-aliasing at colour boundaries. 0=sharp, 1=soft blend.", "description_zh": "颜色边界的抗锯齿程度。0=锐利，1=柔和过渡。推荐 0.5。"},
            {"name": "pixel_spacing", "type": "float", "default": 0.08, "min": 0.05, "max": 0.5,
             "label": "Pixel Spacing (mm)", "label_zh": "像素间距 (mm)", "description": "Resolution of height field", "description_zh": "高度场分辨率（越小越精细，文件越大）"},
            {"name": "format", "type": "choice", "default": "stl", "choices": ["stl", "3mf"],
             "label": "Output Format", "label_zh": "输出格式", "description": "STL + colour map, or Bambu Studio 3MF", "description_zh": "STL + 换色说明，或 Bambu Studio 兼容 3MF"},
        ]
    },
    "triposr": {
        "label": "TripoSR (Fast 3D)",
        "description": "Fast AI image-to-3D using TripoSR. ~2s inference, vertex-color output. Best for quick previews.",
        "label_zh": "TripoSR（快速 3D）",
        "description_zh": "快速 AI 图片转 3D 网格，约 2 秒推理，输出带顶点色的 GLB。适合快速预览和原型验证。",
        "script": "image-to-3d.py",
        "input": "image",
        "accepts": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "gpu": True,
        "params": [
            {"name": "format", "type": "choice", "default": "glb", "choices": ["glb", "obj"],
             "label": "Output Format", "label_zh": "输出格式"},
            {"name": "resolution", "type": "int", "default": 256, "min": 64, "max": 384,
             "label": "Resolution", "label_zh": "分辨率", "description": "Marching cubes grid resolution", "description_zh": "Marching cubes 网格分辨率（越高越精细，越耗显存）"},
            {"name": "foreground_ratio", "type": "float", "default": 0.85, "min": 0.7, "max": 0.95,
             "label": "Foreground Ratio", "label_zh": "前景比例", "description": "Crop ratio for background removal", "description_zh": "背景移除时的裁剪比例"},
            {"name": "no_bg_remove", "type": "bool", "default": False,
             "label": "Skip Background Removal", "label_zh": "跳过背景移除"},
        ]
    },
    "hunyuan": {
        "label": "Hunyuan3D-2.1 (Quality)",
        "description": "High-quality AI image-to-3D using Tencent Hunyuan3D-2.1. ~10-60 min, geometry-only mode.",
        "label_zh": "Hunyuan3D-2.1（高质量）",
        "description_zh": "高质量 AI 图片转 3D 网格，10-60 分钟，几何模式。适合最终模型输出。需要约 7GB 显存。",
        "script": "hunyuan-to-3d.py",
        "input": "image",
        "accepts": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
        "gpu": True,
        "params": [
            {"name": "mode", "type": "choice", "default": "geometry", "choices": ["geometry", "full"],
             "label": "Mode", "label_zh": "模式", "description": "geometry=mesh only, full=with texture (WIP)", "description_zh": "geometry=仅几何，full=含纹理（开发中）"},
            {"name": "steps", "type": "int", "default": 15, "min": 5, "max": 50,
             "label": "Diffusion Steps", "label_zh": "扩散步数", "description": "10-15 for preview, 25-50 for quality", "description_zh": "10-15 步用于预览，25-50 步用于高质量输出"},
            {"name": "resolution", "type": "int", "default": 256, "min": 128, "max": 384,
             "label": "Resolution", "label_zh": "分辨率", "description": "Marching cubes grid resolution", "description_zh": "Marching cubes 网格分辨率"},
            {"name": "seed", "type": "int", "default": 42, "min": 0, "max": 2147483647,
             "label": "Random Seed", "label_zh": "随机种子", "description": "Random seed for reproducibility", "description_zh": "随机种子，用于结果复现"},
            {"name": "format", "type": "choice", "default": "glb", "choices": ["glb", "obj", "stl"],
             "label": "Output Format", "label_zh": "输出格式"},
            {"name": "skip_bg_remove", "type": "bool", "default": False,
             "label": "Skip Background Removal", "label_zh": "跳过背景移除"},
        ]
    },
    "mesh_simplify": {
        "label": "Mesh Simplify",
        "description": "Reduce mesh face count via quadratic decimation, preserving shape.",
        "label_zh": "网格简化 (Simplify)",
        "description_zh": "通过二次误差度量减面，降低面数同时保持模型外观。适合降低打印文件大小和切片速度。",
        "script": "mesh-simplify.py",
        "input": "mesh",
        "accepts": [".glb", ".obj", ".stl", ".gltf"],
        "gpu": False,
        "params": [
            {"name": "target_faces", "type": "int", "default": 50000, "min": 1000, "max": 1000000,
             "label": "Target Faces", "label_zh": "目标面数", "description": "Target face count after simplification", "description_zh": "简化后的目标三角面数量"},
            {"name": "method", "type": "choice", "default": "quadric", "choices": ["quadric", "cluster"],
             "label": "Method", "label_zh": "算法", "description": "quadric=quality preservation, cluster=fast", "description_zh": "quadric=保形质量好，cluster=速度快"},
        ]
    },
    "mesh_smooth": {
        "label": "Mesh Smooth",
        "description": "Apply Taubin smoothing to reduce surface noise while preserving volume.",
        "label_zh": "网格平滑 (Smooth)",
        "description_zh": "使用 Taubin 算法平滑网格表面，去除噪点同时避免体积收缩。适合改善 AI 生成模型的不规则表面。",
        "script": "mesh-smooth.py",
        "input": "mesh",
        "accepts": [".glb", ".obj", ".stl", ".gltf"],
        "gpu": False,
        "params": [
            {"name": "iterations", "type": "int", "default": 3, "min": 1, "max": 20,
             "label": "Iterations", "label_zh": "迭代次数", "description": "Number of smoothing passes", "description_zh": "平滑迭代遍数（越多越光滑，越慢）"},
            {"name": "lambda", "type": "float", "default": 0.5, "min": 0.0, "max": 1.0,
             "label": "Lambda (λ)", "label_zh": "平滑系数 λ", "description": "Taubin lambda — smoothing strength", "description_zh": "Taubin 平滑强度（越大越平滑）"},
            {"name": "mu", "type": "float", "default": -0.53, "min": -1.0, "max": 0.0,
             "label": "Mu (μ)", "label_zh": "反收缩系数 μ", "description": "Taubin mu — negative value prevents shrinkage", "description_zh": "Taubin 反收缩系数（负值防止体积缩小）"},
        ]
    },
    "mesh_scale": {
        "label": "Mesh Scale",
        "description": "Uniformly scale a mesh by factor or to a target physical size.",
        "label_zh": "网格缩放 (Scale)",
        "description_zh": "按比例或目标尺寸缩放网格。适合调整模型到打印平台可容纳的尺寸。",
        "script": "mesh-scale.py",
        "input": "mesh",
        "accepts": [".glb", ".obj", ".stl", ".gltf"],
        "gpu": False,
        "params": [
            {"name": "scale", "type": "float", "default": 1.0, "min": 0.01, "max": 100.0,
             "label": "Scale Factor", "label_zh": "缩放倍数", "description": "Uniform scale multiplier (1.0 = no change)", "description_zh": "均匀缩放倍数（1.0=不变，2.0=放大两倍，0.5=缩小一半）"},
            {"name": "target_width", "type": "float", "default": 0.0, "min": 0.0, "max": 1000.0,
             "label": "Target Width (mm)", "label_zh": "目标宽度 (mm)", "description": "Target max XY dimension (0=use scale factor)", "description_zh": "目标最大长宽尺寸 mm（0=使用缩放倍数）"},
            {"name": "uniform", "type": "bool", "default": True,
             "label": "Uniform", "label_zh": "等比缩放", "description": "Scale all axes equally", "description_zh": "各轴等比缩放"},
        ]
    },
    "views": {
        "label": "Mesh Views",
        "description": "Render 6 orthographic views (front/back/left/right/top/bottom) from a 3D mesh.",
        "label_zh": "六视图 (Views)",
        "description_zh": "从已有 3D 网格渲染六面正交视图（前/后/左/右/上/下），输出 PNG 图片。适合文档和模型验证。",
        "script": "mesh-to-views.py",
        "input": "mesh",
        "accepts": [".glb", ".obj", ".stl", ".gltf"],
        "gpu": False,
        "params": [
            {"name": "resolution", "type": "int", "default": 1024, "min": 256, "max": 4096,
             "label": "Resolution", "label_zh": "分辨率", "description": "Output image resolution per view", "description_zh": "每张视图的输出分辨率"},
            {"name": "no_grid", "type": "bool", "default": False,
             "label": "Skip Grid Image", "label_zh": "跳过组合图", "description": "Only generate individual views", "description_zh": "仅生成单独视图，不生成 3×2 组合图"},
        ]
    },
    "repair": {
        "label": "Mesh Repair",
        "description": "Repair a mesh to be watertight and print-ready. Decimate if needed.",
        "label_zh": "网格修复 (Repair)",
        "description_zh": "修复并封闭网格，输出 3D 打印就绪的 STL。包含去重、填洞、非退化检查和减面。",
        "script": "mesh-repair.py",
        "input": "mesh",
        "accepts": [".glb", ".obj", ".stl", ".gltf"],
        "gpu": False,
        "params": [
            {"name": "output_format", "type": "choice", "default": "stl", "choices": ["stl", "obj", "3mf"],
             "label": "Output Format", "label_zh": "输出格式"},
            {"name": "scale", "type": "float", "default": 1.0, "min": 0.1, "max": 10.0,
             "label": "Scale", "label_zh": "缩放", "description": "Uniform scale factor", "description_zh": "均匀缩放倍数"},
        ]
    },
}

KNOWN_FILE_TYPES = {
    "image": [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
    "mesh": [".glb", ".obj", ".stl", ".gltf", ".glb"],
}
